### ISSUE TITLE
스토어 상품 상세조회

### ISSUE THREAD

**Issue by kagrin97** [wanted-fe-6/wanted-pre-onboarding-fe-6-1-2#7]
- 스토어 상품 상세조회(이미지, 상품 옵션, 수량, 가격 등)
   
- 상품 상세 페이지는 단순 퍼블리싱 영역이므로 제외합니다

**Comment by sunpl13** [comment]
@kagrin97 구매하기 버튼 눌렀을때 props로 상품정보 같이 넘겨주시면 감사하겠습니다~

**Comment by kagrin97** [comment]
url 주소가 어떻게 되죠@sunpl13

**Comment by sunpl13** [comment]
아직 안만들어놨어요
근데 fruit/:id가 상세조회니까

fruit/:id/payment로 해주시면 될 것 같습니당

**Comment by kagrin97** [comment]
> @kagrin97 구매하기 버튼 눌렀을때 props로 상품정보 같이 넘겨주시면 감사하겠습니다~

props로 fruit, volume 각각 제품과 수량을 넘겨줬습니다.
